### ISSUE TITLE
Help with installing into Nuxt.js

### ISSUE THREAD

**Issue by 8BitJonny** [nolimits4web/atropos#11]
# Nuxt.js Installation: Help Wanted
Hey 👋🏼 
I know this is not the really a good kind of issue that I'm creating here, but since this amazing project is still relatively unknown and I couldn't find any help anywhere else on the web, I though I'd post it here.
But please close this issue if you don't want this type of "Help wanted" issue

I can't get your library installed with nuxt.js. I spend a few days already and thought, I'd see if anyone here can get it to work.

## Problem
It is always saying
```
This dependency was not found:
* atropos/css
* atropos/vue
```

## Problem Demonstration
https://codesandbox.io/s/broken-smoke-bjh6y?file=/nuxt.config.js
This is a sandbox demonstrating my issue.

Anyone help is much appreciated 🙏🏼

**Comment by PMLS3** [comment]
Hi @8BitJonny , how did you make it work with Nuxt3? Thank you in advance
