### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by Jeromearsene** [nolimits4web/atropos#33]
### Clear and concise description of the problem

Add types

### Suggested solution

Use Typescript

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/atropos/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://atroposjs.com/docs).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
TypeScript support is there
