### ISSUE TITLE
Module not found: Can't resolve 'atropos/react'

### ISSUE THREAD

**Issue by Frhazz** [nolimits4web/atropos#5]
Hi, 
I'm trying to implement Atropos in a project but it seems it can't find the module.
I installed the package via npm i atropos and imported it in my component like indicated in the guide:
import Atropos from 'atropos/react'.

**Comment by asyam1** [comment]
@Frhazz Was looking through the old closed Issues  #4, tried importing "atropos/react/atropos-react.esm" instead of "atropos/react" and it seems to find the module.

**Comment by razekteixeira** [comment]
@Frhazz @asyam1 

The solution is to use a newer version of nodejs which supports es modules. Try to use the lib with node >= 14 for example. Everything works exactly as expected (already tested it with react, Vue and vanilla js) :)

**Comment by jonathanlal** [comment]
I'm using node 16 - doesn't work... Module not found

**Comment by MtDalPizzol** [comment]
Having the same problem here with Node 18.2.0.
